- src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
- src/main/java/com/ureca/gate/global/util/redis/CacheKeyUtil.java
- src/main/java/com/ureca/gate/member/application/AuthenticationServiceImpl.java
- src/main/java/com/ureca/gate/member/application/MemberServiceImpl.java
- src/main/java/com/ureca/gate/member/controller/MemberController.java
- src/main/java/com/ureca/gate/member/controller/inputport/AuthenticationService.java
- x
- 캐시 내 refreshToken 삭제, accessToken 블랙리스트 처리
- AuthenticationServiceImpl 클래스 내 하드 코딩 CacheKeyUtil로 관리
- x
- [추가] : No
> feat: [GATE-84] 로그아웃 구현

- src/main/java/com/ureca/gate/global/filter/JwtAuthenticationFilter.java
- src/main/java/com/ureca/gate/global/util/redis/CacheKeyUtil.java
- src/main/java/com/ureca/gate/member/application/AuthenticationServiceImpl.java
- src/main/java/com/ureca/gate/member/controller/MemberController.java
- src/main/java/com/ureca/gate/member/controller/inputport/AuthenticationService.java
- src/main/java/com/ureca/gate/member/controller/response/TokenReissueResponse.java
- x
-  캐시 내, refreshToken과 요청 헤더에 있는 refreshToken와 비교 후, 일치시 accessToken 응답
- x
- [추가] : No
> feat: [GATE-85] 토큰 재발급

- src/main/java/com/ureca/gate/member/controller/MemberController.java
- x
-백엔드에서 "http://localhost:5173/auth/kakao"쪽으로 토큰과 상태값을 리다이렉션 시킴
- 
- [추가] : No
> refactor : 소셜로그인 처리

- src/main/java/com/ureca/gate/global/config/security/SecurityConfig.java
- x
-  SecurityConfig클래스내   .cors(Customizer.withDefaults()) 추가
- x
- [추가] : No
> refactor: cors에러 수정

- src/main/java/com/ureca/gate/dog/application/ProfileServiceImpl.java
- src/main/java/com/ureca/gate/dog/application/outputport/DogRepository.java
- src/main/java/com/ureca/gate/dog/controller/ProfileController.java
- src/main/java/com/ureca/gate/dog/controller/inputport/ProfileService.java
- src/main/java/com/ureca/gate/dog/controller/response/ProfileResponse.java
- src/main/java/com/ureca/gate/dog/domain/Dog.java
- src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/DogJpaRepository.java
- src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/DogRepositoryImpl.java
- src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/entity/DogEntity.java
- src/main/java/com/ureca/gate/global/util/file/FileStorageService.java
- src/main/java/com/ureca/gate/global/util/s3/S3FileManager.java
- src/test/java/com/ureca/gate/dog/domain/DogTest.java
> feat: 반려견 프로필 API & S3 파일 삭제

- src/main/java/com/ureca/gate/member/application/MemberServiceImpl.java
- src/main/java/com/ureca/gate/member/controller/MemberController.java
- src/main/java/com/ureca/gate/member/controller/inputport/MemberService.java
- src/main/java/com/ureca/gate/member/controller/response/MemberInfoResponse.java
> feat: [GATE-50] 회원정보 조회 API

- src/main/java/com/ureca/gate/place/application/CityListServiceImpl.java
- src/main/java/com/ureca/gate/place/application/outputport/CityRepository.java
- src/main/java/com/ureca/gate/place/application/outputport/PlaceCategoryRepository.java
- src/main/java/com/ureca/gate/place/controller/PlaceController.java
- src/main/java/com/ureca/gate/place/controller/inputport/CityListService.java
- src/main/java/com/ureca/gate/place/controller/response/CityResponse.java
- src/main/java/com/ureca/gate/place/domain/City.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/CityJpaRepository.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/CityRepositoryImpl.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceCategoryRepositoryImpl.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/CityEntity.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/vo/Address.java
- X
- 지역리스트 조회 API 구현
- place 내 city 테이블로 분리하여 관리
- x
- [데이터베이스 변경사항 여부] : YES
- place 내 city 테이블로 분리
- [추가] : No
> feat:  [GATE-71] 지역리스트 조회 API 구현

- src/main/java/com/ureca/gate/favorites/application/FavoritesServiceImpl.java
- src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
- src/main/java/com/ureca/gate/favorites/controller/FavoritesController.java
- src/main/java/com/ureca/gate/favorites/controller/inputport/FavoritesService.java
- src/main/java/com/ureca/gate/favorites/controller/response/FavoritesEnrollResponse.java
- src/main/java/com/ureca/gate/favorites/controller/response/FavoritesResponse.java
- src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesJpaRepository.java
- src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
- x
- 즐겨찾기 서비스 로직 구현 (memberId 기준으로 즐겨찾기 조회)
- FavoritesRepository에서 place와 함께 조회하도록 fetch join을 통해 한꺼번에 조회
- 페이징 처리를 해야할 거 같기도 함. 
- [추가] : No
> feat: [GATE-56] 즐겨찾기 리스트 조회 기능 구현

- src/main/java/com/ureca/gate/place/controller/response/PlaceResponse.java
- src/main/java/com/ureca/gate/place/infrastructure/dto/PlaceResponse.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustomImpl.java
- x
-   장소 리스트 응답 내 위도,경도 추가
-  x
- [추가] : No
> fix: [GATE-32] 장소 리스트 응답 내 위도,경도 추가

- src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
- src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesJpaRepository.java
- src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
- src/main/java/com/ureca/gate/place/application/PlaceDetailServiceImpl.java
- src/main/java/com/ureca/gate/place/controller/PlaceController.java
- src/main/java/com/ureca/gate/place/controller/inputport/PlaceDetailService.java
- src/main/java/com/ureca/gate/place/controller/response/PlaceDetailResponse.java
- x
- @AuthenticationPrincipal Long memberId를 통해서 로그인했을 경우와 안 했을경우를 나뉘어 즐겨찾기 여부 확인
- 
- [추가] : No
> refactor: [GATE-38] 장소 내 즐겨찾기 여부 추가

- src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
- src/main/java/com/ureca/gate/place/application/outputport/CityRepository.java
- src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/CityRepositoryImpl.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
- src/main/java/com/ureca/gate/plan/application/PlanServiceImpl.java
- src/main/java/com/ureca/gate/plan/application/outputport/PlanRepository.java
- src/main/java/com/ureca/gate/plan/controller/PlanController.java
- src/main/java/com/ureca/gate/plan/controller/inputport/PlanService.java
- src/main/java/com/ureca/gate/plan/controller/response/PlaceInfo.java
- src/main/java/com/ureca/gate/plan/controller/response/PlanPlaceResponse.java
- src/main/java/com/ureca/gate/plan/controller/response/PlanResponse.java
- src/main/java/com/ureca/gate/plan/domain/Plan.java
- src/main/java/com/ureca/gate/plan/domain/PlanPlace.java
- src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/PlanRepositoryImpl.java
- src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/entity/PlanEntity.java
- src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/entity/PlanPlaceEntity.java
- src/test/java/com/ureca/gate/plan/domain/PlanPlaceTest.java
- src/test/java/com/ureca/gate/plan/domain/PlanTest.java
-
- 일정 생성 API - 리팩토링
- 일정 조회 API
- 
- [추가] : No
> feat: [GATE-75] 일정 조회 API

- src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
- src/main/java/com/ureca/gate/favorites/controller/response/FavoritesResponse.java
- src/main/java/com/ureca/gate/favorites/infrastructure/dto/FavoritesIdWithPlaceDto.java
- src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
- X
- favoritesId 응답값 추가 및 profileUrl 삭제
- DTO 변환 로직 추가
- Repository와 Service 계층 간 데이터 흐름 개선
- x
- [추가] : No
> refactor: [GATE-56]  즐겨찾기 리스트 조회시 응답값 수정

- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilder.java
- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
-
- 0.1 스코어 미만은 출력 안 되게끔 수정
- 
- [추가] : No
> fix : 0.1 스코어 미만은 출력 안 되게끔 수정

- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilder.java
-
- fix : 검색어가 없을 시, minScore 설정 삭제
- 
- [추가] : No
> fix : 검색어가 없을 시, minScore 설정 삭제

- src/main/java/com/ureca/gate/global/util/city/CityMapper.java
> fix : 매핑 지역명 수정

- src/main/java/com/ureca/gate/place/controller/response/PlaceSearchForMapResponse.java
-
-  distance값 응답에 포합되도록 수정
- 
- [추가] : No
> fix: [GATE-88] dto응답값 수정

- src/main/java/com/ureca/gate/place/controller/PlaceController.java
-
- PlaceController-GetPlacesBySearch 메소드 Default Size 설정
- 
- [추가] : No
> fix: [GATE-88] PlaceController-GetPlacesBySearch 메소드 Default Size 설정

- src/main/java/com/ureca/gate/global/dto/response/PageResponse.java
- src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
- src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
- src/main/java/com/ureca/gate/place/controller/PlaceController.java
- src/main/java/com/ureca/gate/place/controller/inputport/PlaceForMapService.java
- src/main/java/com/ureca/gate/place/infrastructure/command/PlaceSearchCommand.java
- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilders.java
- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceJpaRepository.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
-
- script_fields를 활용하여 거리(distance) 계산 및 반환
- PlaceSearchCommand에 거리 값을 포함하여 응답 생성
- CustomPage로 결과 반환
- 
- [추가] : No
> refactor: script_fields를 활용하여 거리(distance) 계산하도록 수정

- src/main/java/com/ureca/gate/place/application/PlaceDetailServiceImpl.java
- src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
- src/main/java/com/ureca/gate/place/controller/PlaceController.java
- src/main/java/com/ureca/gate/place/controller/inputport/PlaceForMapService.java
- src/main/java/com/ureca/gate/place/controller/response/PlaceDetailResponse.java
- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
-
-  장소 검색 페이징 삭제 / 장소 상세 조회 위도/경도 필수 삭제
- 
- [추가] : No
> fix : 장소 검색 페이징 삭제 / 장소 상세 조회 위도/경도 필수 삭제

- src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
- src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
- src/main/java/com/ureca/gate/place/controller/PlaceController.java
- src/main/java/com/ureca/gate/place/controller/inputport/PlaceForMapService.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustom.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustomImpl.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
-
- 반경 검색시, 잘못된 위치 거리 계산 수정 ( 원래 내 위치(위도,경도) 파라미터 추가)
- 
- [추가] : No
> fix :  반경 검색시, 잘못된 위치 거리 계산 수정

- src/main/java/com/ureca/gate/global/exception/custom/RouteNotFoundException.java
- src/main/java/com/ureca/gate/global/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/ureca/gate/plan/application/PlanRouteServiceImpl.java
-
- 일정 최단 경로 API 에러 응답코드 수정
- 
- [추가] : No
> feat: [GATE-73] 일정 최단 경로 API 에러 응답코드 수정

- src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
- src/main/java/com/ureca/gate/place/application/outputport/PlaceElasticRepository.java
- src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
- src/main/java/com/ureca/gate/place/controller/PlaceController.java
- src/main/java/com/ureca/gate/place/controller/inputport/PlaceForMapService.java
- src/main/java/com/ureca/gate/place/controller/response/PlaceForMapResponse.java
- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustom.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustomImpl.java
- src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
-
- 마감 기한 이슈로 인한 분리된 API 병합 추후 리펙토링 예정
- 잘 분리되어있던 코드 통합으로 인한 분리된 코드 주석처리
- 분리되어있던 코드 통합으로 인한 에러 발생가능성 존재 확인바람.
- [추가] : No
> fix : [GATE - 88] 검색어 기반 장소 검색 & 반경 기반 장소 검색 API 통합

- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/Document/PlaceElastic.java
-
- Elasticsearch 응답의 _class 필드 무시 처리
- 
- [추가] : No
> fix : [GATE-88] Elasticsearch 응답의 _class 필드 무시 처리

- src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
-
- 검색어 없이 지역명만 검색시 검색어에 지역명 넣기
- 
- [추가] : No
> fix : 검색어 없이 지역명만 검색시 검색어에 지역명 넣기

- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilder.java
- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilders.java
- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/Document/PlaceElastic.java
- src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
-
- fix : 오류 수정
- 
- [추가] : No
> fix : 오류 수정
